### ISSUE TITLE
Python 3 incompatibility in the example scripts

### ISSUE THREAD

**Issue by gmonig** [SiLab-Bonn/beam_telescope_analysis#9]
When executing the example scripts with Python3, one gets the following error (it works with Python2):

Traceback (most recent call last):
  File "/home/gianna/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integerDuring handling of the above exception, another exception occurred:Traceback (most recent call last):
  File "eutelescope.py", line 349, in <module>
    run_analysis(hit_files=hit_files)
  File "eutelescope.py", line 130, in run_analysis
    select_reference_dut=0)
  File "/home/gianna/beam_telescope_analysis/beam_telescope_analysis/dut_alignment.py", line 257, in prealign
    accumulator, theta, rho, theta_edges, rho_edges = analysis_utils.hough_transform(hough_data, theta_res=0.1, rho_res=1.0, return_edges=True)
  File "/home/gianna/beam_telescope_analysis/beam_telescope_analysis/tools/analysis_utils.py", line 919, in hough_transform
    thetas = np.linspace(-90.0, 0.0, np.ceil(90.0 / theta_res) + 1)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/gianna/anaconda3/lib/python3.6/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by ChristianBesp** [comment]
I second this. I think, #7 would solve this

**Comment by laborleben** [comment]
Ok, thanks. This is a duplicate, so I close this.
